# Generated by Django 5.2.4 on 2025-08-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('forgot_key', models.CharField(blank=True, max_length=128, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('pertner', 'Partner')], max_length=10)),
            ],
        ),
    ]
