# Generated by Django 5.2.4 on 2025-08-25 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicant_otherinformation_relative_skillsexperience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('selected_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection_status', to='app.applicant')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_applicants', to='app.user')),
            ],
        ),
    ]
