# Generated by Django 5.2.4 on 2025-08-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='full_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applicants/full_photos/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applicants/passport_photos/'),
        ),
    ]
