# Generated by Django 5.2.4 on 2025-08-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_applicant_full_photo_applicant_passport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='passport_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
