# Generated by Django 5.2.4 on 2025-08-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_applicant_passport_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='full_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passport_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
